--- 
title: "RMC-TotalRisk User's Guide"
author: "C. Haden Smith and Woodrow L. Fields"
date: "`r paste('Last updated:', Sys.Date())`"
site: bookdown::bookdown_site
output: bookdown::bs4_book
documentclass: book
bibliography: [book.bib]
csl: ieee.csl
link-citations: yes
github-repo: "USACE-RMC/RMC-TotalRisk"
url: 'https://usace-rmc.github.io/RMC-TotalRisk-Users-Guide/1_0/'
favicon: "TotalRiskIcon.ico"
description: "This is a user's guide for working with the quantitative risk analysis software, RMC-TotalRisk."
keywords: ["RMC-TotalRisk",  "USACE", "Risk Management Center", "Dam and Levee Safety", "life safety", "user's guide", "quantitative risk analysis", "system risk", "uncertainty analysis", "failure modes"]
robots: "index, follow"
mathsize: 0.9
version: "1.0"
---

# Preface {-}

The U.S. Army Corps of Engineers TotalRisk software (RMC-TotalRisk) performs quantitative risk calculations for a system from a set of hazard, transform, system response, and consequence functions. RMC-TotalRisk is part of an integrated software suite that supports risk assessments. The software features a fully integrated modeling platform, including a modern graphical user interface, data entry, report quality charts, and diagnostic tools. RMC-TotalRisk can evaluate risk for a single component with multiple failure modes and a complex system comprised of multiple components. This document is a guide for developing a quantitative risk analysis with RMC-TotalRisk.

## Acknowledgements {-}

RMC-TotalRisk would not exist without the support of Risk Management Center (RMC) leadership, in particular RMC Director Nathan Snorteland and Lead Engineers David Margo, Jason Needham, and Timothy O’Leary. The authors also recognize David Bowles and Ruben Jongejan for performing an external peer review of the software and risk analysis framework. The software development team is very grateful to those who contributed to the software.

## How to Cite This Guide {-}

If you would like to cite this User's Guide, please use the following format:

```{block, type='citation-note'}
C. H. Smith and W. L. Fields, *RMC-TotalRisk user's guide*, Version 1.0. Lakewood, CO: U.S. Army Corps of Engineers, Risk Management Center, 2025. Accessed on <span class="current-date">&lt;enter current date here&gt;</span>.
```
