name: Build and Deploy Multiple Sites

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Step 3: Install dependencies
    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("bookdown"))'

    # Step 4: Build the User Guide
    - name: Build User Guide
      working-directory: ./User's Guide
      run: |
        Rscript -e 'bookdown::render_book(output_format = "all")'

    # Step 5: Build the Technical Reference Manual
    #- name: Build Technical Reference Manual
    #  working-directory: ./Technical Reference Manual
    #  run: |
    #    Rscript -e 'bookdown::render_book(output_format = "all")'

    # Step 6: Deploy to GitHub Pages (docs/)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
